// app/layout.js

export const metadata = {
  title: "dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <h1>dashboard</h1>
        </header>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
